metal-toolbox/audito-maldito

.chainguard/source.yaml
This is needed for sigstore-powered commit signing
=> Add chainguard configuration

.github/workflows/release.yml
This is the last bit for the GitHub Actions migration.
=> Release container image through GitHub as part of release

internal/common/nodename.go, internal/common/nodename_test.go
This enables users running audito-maldito outside of k8s to require less
setup.
=> Fall back to using `gethostname` if no `NODE_NAME` environment variable is given

.golangci.yml, go.mod, go.sum, internal/auditd/auditd_test.go
Refer to the following URLs for more information:
- https://github.com/metal-toolbox/go-libaudit/pull/3
- https://github.com/elastic/go-libaudit/issues/127
=> go-libaudit: Use metal-toolbox fork for issue 127.

internal/auditd/auditd.go
During deployment, we found that audito-maldito would deadlock when writing a UserLogin event to the RemoteUser logins channel (see "internal/journald/processentry.go", line 240).
We found that the go-libaudit Reassembler.Close method was executing our reassembler call-back's methods - which results in a write to the reassembleAuditdEvents channel. When coupled with a "defer" statement, the Close method deadlocked because:
- The context.Context was not marked as done
- No Go routines are reading from reassembleAuditdEvents
The Reassembler.Close method should *really* reflect that it calls the reassembler callback.
=> auditd: Temporary "fix" for deadlock.

internal/auditd/sessiontracker.go, internal/auditd/sessiontracker_test.go, internal/common/genericsyncmap.go
This makes the session tracker use thread-safe constructs for storing and accessing the session ID to users and the PID to Remote User Login maps.
To do this, I created a generic map structure that locks it's contents with a mutex for safe concurrent access.
In order to test this further, Added more thorough testing and documentation to `TestSessionTracker_AuditdEvent_ExistingSession_Ended` which seemed like a relevant function to verify.
Since the session tracker can now be parallelized, the `TestSessionTracker_AuditdEvent_NoSessionID` test was marked and modified as such.
=> Make sessiontracker use thread-safe constructs

internal/journald/processentry.go
We were currently dropping events when a non certificate remote login attempt happened and the user was unknown.
e.g. This only logged this message but no event:
```json
{
"level": "info",
"ts": 1680689060.9600282,
"caller": "journald/processentry.go:179",
"msg": "a: got login entry with no matches for certificate identifiers"
}
```
For this type of entry:
```
Apr 05 12:44:05 ynot-dev-box-12314 sshd[149010]: Accepted publickey for root from 89.18.65.131 port 60268 ssh2: ED25519 SHA256:qZqq9LIYI5PqrbackEJWI6qjydwiQzkC1z0NrwSCC10
Apr 05 12:44:05 ynot-dev-box-12314 sshd[149010]: pam_unix(sshd:session): session opened for user root by (uid=0)
```
Note: This does not add details for password logins.
=> Fix: Not logging when no certificate but success login

internal/auditd/auditd.go, internal/auditd/auditd_test.go, internal/auditd/reassembler_callback.go, internal/auditd/sessiontracker/audit_interface.go, internal/auditd/sessiontracker/fakes/fakes.go, internal/auditd/sessiontracker/sessiontracker.go
This uses the session tracker directly in the reassembler callback in
order to remove one level of channel message passing.
To do this, the sessiontracker now introduces an interface called
`Auditor` which will output audit messages as called in a non-blocking
manner in terms of threading (it blocks on IO).
Errors are still passed to a channel, but it is now a channel just
dedicated towards errors.
A fake `Auditor` was introduced in order to allow for easier testing through
a callback function interface.
=> Remove one level of channels using session tracker directly

internal/journald/reader.go, internal/metrics/constants.go, internal/metrics/metrics.go
This adds a metrics counter for the total of errors in audito maldito.
The metric is called `audito_maldito_errors_total`. It has a single
label called `type` which currently only picks up errors for
journald read errors. The type is hardcoded to `journald_wait`.
The guidance is that we should only add errors to this metric that we
should alert on, this way we can write proper alertmanager rules for
this.
=> Add metrics for total of errors

internal/health/health_test.go
The unit tests were testing values at random, but the randomness had a
logical error. That is, it may have tested 0 services for readiness,
which is not what we wanted to test.
This removes the randomness from these tests, as it's not necessary to
add entropy to test the functionality we need. This logical error is a
carry-over from the initial implementation of the readiness logic.
=> health: Fix unit tests

internal/app/app.go
This reverts the default logging to `error` level from `debug`.
=> Revert default logging from debug to error

internal/health/health.go
Prior to this change, the readiness HTTP endpoint would always write a HTTP 200 status code header - even if the application was not ready.
This happened because we indirectly call http.ResponseWriter.Write when we stream the readiness status map to the HTTP client. This occurs when we execute "json.NewEncoder(w).Encode(...)".
Executing http.ResponseWriter.Write results in an implicit call to http.ResponseWriter.WriteHeader, with the default value being a 200 status code. [1] Subsequent calls to WriteHeader are ignored by the http library. As a result, we were always setting the HTTP response status code header to 200. This behavior is likely meant to reflect how HTTP should work; HTTP headers are written to the peer before the body is written.
1. …
=> internal/health: Fix static readiness HTTP status.

README.md, internal/health/health.go
This warning was true at one point. Since then, the log rotation logic has been updated to retry when a failure occurs. The logic has also been improved to better identify when a rotation occurred.
=> readme: Remove defunct warning about log rotation.

cmd/app.go, ingesters/journald/reader.go, processors/rocky/rockyprocessor.go, processors/rocky/rockyprocessor_test.go, processors/sshd/sshdprocessor.go, processors/sshd/sshdprocessor_test.go, processors/varlogsecure/varlogsecure.go
Refactors processentry to a struct named SshdProcessor.
Exposes a method called ProcessSshdLogEntry that accepts a ctx
and a SshdLogEntry to simplify waht the ingesters need to call.
SshdLogEntry is a pogs (plain old go struct) that has two strings - Message and PID.
=> Creates sshdprocessor struct

ingesters/auditlog/auditlogingester.go, ingesters/auditlog/auditlogingester_test.go, ingesters/journald/reader.go, ingesters/namedpipe/namedpipeingester.go, ingesters/namedpipe/namedpipeingester_test.go, ingesters/rocky/fakes/sshdporcessorfaker.go, ingesters/rocky/rockyingester.go, ingesters/rocky/rockyingester_test.go, ingesters/rocky/testdata/secure.log, ingesters/syslog/fakes/sshdporcessorfaker.go, ingesters/syslog/syslogingester.go, ingesters/syslog/syslogingester_test.go, processors/rocky/rockyprocessor.go, processors/sshd/sshdprocessor.go, processors/sshd/sshdprocessor_test.go, processors/varlogsecure/varlogsecure.go
* auditlog ingester reads from a named pipe that contains content from /var/log/audit/audit.log\
* syslog ingester reads from a named pipe that contains content from a PID and the msg from syslog / journald
* rocky processor reads from a named that contains content from /var/log/secure
=> * Adds in named pipe ingesters:

processors/auditd/auditd.go, processors/auditd/auditd_good_test.go, processors/auditd/auditd_test.go
This unit test (renamed in the commit for accuracy) was failing intermittently due to the cancellation of the context.Context racing with a channel write to a buffered channel (well, that is what I think was happening anyways).
This commit updates the problematic test to use the TestAuditEncoder.Err field, which is checked by the Write method prior to writing the AuditEvent - thus avoiding any races / inconsistent behavior.
=> auditd: Make test reliable w/ TestAuditEncoder.Err,

processors/auditd/auditd_test.go, processors/auditd/sessiontracker/errors.go, processors/auditd/sessiontracker/sessiontracker.go, processors/auditd/sessiontracker/sessiontracker_test.go
The auditEventFail field was overloaded to represent two different failures scenarios:
- PID parse failures
- Failures when writing to the AuditEventWriter.
This commit makes the failures explicit.
=> auditd: Clarify SessionTrackerError failures.

processors/sshd/openssh_regex.go, processors/sshd/sshdprocessor.go
The "var" block will continue to grow in size as we add support for other OpenSSH log messages. This commit moves the regex into their own source file. In theory, this will make reading the existing source file easier.
=> sshd: Move OpenSSH log regex into separate file.

.github/workflows/test.yml
This is to work around proxying issues in GitHub
=> Explicitly set goproxy to use proxy and direct to fetch packages

processors/auditd/reassembler_callback.go
Prior to this change, I noticed TestAuditd_Read_AuditEventWriterError would occasionally fail with the error: "panic: test timed out after 10m0s". This can be seen in the linked GitHub CI run. [1]
I was able to reproduce this failure by re-running the test several times locally. [2] I am not entirely sure what the failure is caused by, as adding logging caused the issue to stop occurring). Looking at the CI log, it seems like the ReassemblyComplete method was called by two different Go routines. The Go routines became blocked trying to write to the errors channel. [1]
I noticed that the reassemblerCB callback does not bound the errors channel write with any other event. As a result, a blocked write will cause a deadlock.
There are at least two ways to deal with this:
1. Bound the errors …
=> auditd: Give up writing error if channel full.

processors/sshd/openssh_regex.go, processors/sshd/user_type_test.go
The processAcceptedPasswordEntry function was untested. I also added some additional characters to the "exp" test constants.
=> sshd: Use '.*' for regex. Add accept pw test.

cmd/namedpipe.go, internal/common/namedpipe.go, internal/common/namedpipe_test.go
In discussions with the team, we decided that the input files will always be named pipes. As a result, we felt it was necessary to enforce a file-type check that produces a helpful error message.
=> main: Exit if input files are not named pipes.

go.mod
Dont use `nxadm/tail` since rsyslog tails the audit.log file for us
=> removes-unused-package-nxadm-tail

.github/workflows/release.yml
This commit adds cosign to the CI pipeline for the audito-maldito container image only. A future commit will add cosign support for the rsyslog container image. A separate commit is required because we tag the rsyslog image with the same name as the audito-maldito image and append "-rsyslog" to the image tag. We will address this separately to simplify the overall code changes.
cosign is an open-source tool developed by Chainguard that signs container images, allowing other users to cryptographically verify the origin of container images. [1]
cosign has different operating modes. This commit utilizes Chainguard's signing infrastructure via "keyless signing". [2] Keyless signing makes image signing easy for open-source projects because Chainguard operates the signing infrastructure on …
=> ci: Use cosign to sign audito-maldito image.
